name: check_syntax
on:
  push:
    branches: [ main ]
jobs:
  syntax-check:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install flake8
      run: pip install flake8
    - name: Show Python version
      run: python --version
    - name: Check code with flake8
      run: flake8 .
