name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  check_syntax:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        (Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py) -and (python get-pip.py --force-reinstall)

    - name: Install flake8
      run: |
        python -m pip install flake8

    - name: Display Python version
      run: python --version

    - name: Run flake8
      run: |
        python -m flake8

