name: Check Python Version

on:
  push:
    branches:
      - main

jobs:
  check_python_version:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pip
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
        python -m pip --version

    - name: Display Python Version
      run: python --version
